### ISSUE TITLE
HTTP error 403 when querying FHRS API 'Establishments' endpoint

### ISSUE THREAD

**Issue by gregrs-uk** [gregrs-uk/python-fhrs-osm#21]
There was an error running the dev server's update script this morning:

```
Traceback (most recent call last):
 File "get_fhrs_data.py", line 34, in <module>
   xmlstring = fhrs.download_establishments_for_authority(this_authority)
 File "/home/gregrs/python-fhrs-osm/fhrs_osm/__init__.py", line 875, in download_establishments_for_authority
   return self.api_download(endpoint=endpoint)
 File "/home/gregrs/python-fhrs-osm/fhrs_osm/__init__.py", line 856, in api_download
   except URLError:
NameError: global name 'URLError' is not defined
```

I think on [this line](https://github.com/gregrs-uk/python-fhrs-osm/blob/master/fhrs_osm/__init__.py#L856) `URLError` needs changing to `urllib2.URLError`. Will check this ASAP.

**Comment by gregrs-uk** [comment]
This hasn't been a problem before. I'm thinking maybe the FHRS API was down and so this (incorrectly named) exception was raised for the first time...

**Comment by gregrs-uk** [comment]
The FHRS API doesn't appear to be responding normally to requests such as `Establishments?localAuthorityId=371`. This will need further investigation.

**Comment by gregrs-uk** [comment]
The FHRS API is returning HTTP error 403 when querying its Establishments endpoint. I have just emailed the webmaster.

```
HTTP Error when trying to get data from FHRS API
URL: http://api.ratings.food.gov.uk/Establishments?localAuthorityId=371
Headers: [('X-api-version', 2), ('Host', 'api.ratings.food.gov.uk'), ('Content-type', 'application/xml'), ('Accept', 'application/xml'), ('User-agent', 'python-fhrs-osm')]
...
urllib2.HTTPError: HTTP Error 403: Usage restricted
```

**Comment by gregrs-uk** [comment]
No reply from the webmaster yet so I have forwarded my enquiry to the general helpline email address.

**Comment by gregrs-uk** [comment]
Strangely, the 403 error can be avoided by adding some other variables to the query. This can be verified using the [FHRS API test page](http://api.ratings.food.gov.uk/Help/Api/GET-Establishments_name_address_longitude_latitude_maxDistanceLimit_businessTypeId_schemeTypeKey_ratingKey_ratingOperatorKey_localAuthorityId_countryId_sortOptionKey_pageNumber_pageSize). I have added pageNumber and pageSize since these appear to default to 1 and 5000 anyway.

**Comment by gregrs-uk** [comment]
Fixed and dev server update completed successfully. As a result of investigating FHRS API, opened issue #22.
